In [1]:
import pandas as pd

In [2]:
gap_train= pd.read_pickle('./temp_result/train_kaggle_processed_PPA_PCA_PPA_neither.p')
gap_test= pd.read_pickle('./temp_result/test_kaggle_processed_PPA_PCA_PPA_neither.p')
gap_valid= pd.read_pickle('./temp_result/valid_kaggle_processed_PPA_PCA_PPA_neither.p')

In [3]:
gap_train.head()

,ID,Text,Pronoun,Pronoun-offset,A,A-offset,A-coref,B,B-offset,B-coref,...,pron_idx,A_vector,B_vector,pron_vector,name_list,name_list_2,neither_idx,neither_idx_2,neither_vector,neither_vector_2
0,test-1,Upon their acceptance into the Kontinental Hoc...,His,383,Bob Suter,352,False,Dehner,366,True,...,[109],"[[-0.16258414, 0.7170149, -0.16182709, 0.33984...","[[0.46089026, 0.8022368, -0.26556754, 0.248125...","[[0.6202348, -0.49657542, 0.5204739, -0.727411...","[(Dehner, 58), (Gary, 320), (Suter, 325), (Bob...","[(Gary, 320), (Ryan, 432)]","[13, 14, 15, 85, 86, 87, 88, 120, 121, 122, 123]","[85, 86, 120, 121]","[[0.43322292, 0.79829735, -0.15718476, 0.42089...","[[0.7398826, 0.26755247, 0.29362696, 0.3004961..."
1,test-2,"Between the years 1979-1981, River won four lo...",him,430,Alonso,353,True,Alfredo Di St*fano,390,False,...,[113],"[[-0.37001002, 0.51947534, 0.41240457, -0.0459...","[[0.66546816, 0.78631735, 0.57873654, 0.009659...","[[0.6709301, -0.5158502, 0.73226666, -0.564204...","[(Alonso, 353), (Alfredo, 390), (Di, 398), (St...","[((, 409), (Carlos, 493), (Daniel, 500), (Tapi...","[109, 125, 126, 127, 128, 129, 130, 131, 133, ...","[109, 125, 126, 127, 128, 129, 130, 131, 133, ...","[[0.4568775, 0.943457, -1.0240802, 0.35397953,...","[[0.4568775, 0.943457, -1.0240802, 0.35397953,..."
2,test-3,Though his emigration from the country has aff...,He,312,Ali Aladhadh,256,True,Saddam,295,False,...,[81],"[[-0.13203266, 1.3001504, 1.0933744, 0.0792686...","[[0.08869687, 0.7399757, -0.47687554, 0.293353...","[[0.37514523, -0.4730158, 0.10452151, -0.03368...","[(Kamel, 75), (Hussien, 139), (Ali, 177), (Ala...","[(Kamel, 75), (Hussien, 139)]","[13, 14, 28, 29, 30, 40, 41, 42, 43, 44, 45]","[13, 14, 28, 29, 30]","[[-0.24583033, 0.5785628, -0.45035437, 0.90760...","[[-0.24583033, 0.5785628, -0.45035437, 0.90760..."
3,test-4,"At the trial, Pisciotta said: ``Those who have...",his,526,Alliata,377,False,Pisciotta,536,True,...,[141],"[[-0.43812943, 0.23181425, -1.1097318, 0.02765...","[[-0.76229733, -0.70085824, -0.23845942, -0.59...","[[0.6802153, -0.041674256, 0.36125743, 0.46846...","[(Pisciotta, 14), (Bernardo, 78), (Mattarella,...","[(Bernardo, 78), (Mattarella, 87), (Marchesano...","[5, 6, 7, 8, 22, 23, 24, 25, 26, 27, 30, 31, 3...","[22, 23, 24, 25, 26, 27, 39, 40, 41, 44, 45, 4...","[[-0.63530976, 0.19418138, -0.26388228, 0.1768...","[[0.041738294, -0.06563458, -0.31707367, -0.90..."
4,test-5,It is about a pair of United States Navy shore...,his,406,Eddie,421,True,Rock Reilly,559,False,...,[110],"[[-0.3663241, 1.0233932, -0.040710405, -1.4244...","[[1.2342895, -0.16074917, -0.08441551, 0.13165...","[[0.31947732, -0.5680447, 1.1254325, -0.703441...","[(Tom, 65), (Berenger, 69), (William, 82), (Mc...","[(Tom, 65), (Berenger, 69), (William, 82), (Mc...","[18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 3...","[18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 3...","[[0.6178753, 0.7156216, 0.06808539, 0.4111841,...","[[0.6178753, 0.7156216, 0.06808539, 0.4111841,..."

In [4]:
def is_topic(name, topic):
    for i in name:
        if i in topic:
            return 1
    return 0

In [5]:
gap_train['topic'] = gap_train['URL'].apply(lambda x: x.split('/')[-1].split('_'))
gap_valid['topic'] = gap_valid['URL'].apply(lambda x: x.split('/')[-1].split('_'))
gap_test['topic'] = gap_test['URL'].apply(lambda x: x.split('/')[-1].split('_'))

In [6]:
gap_train['topic_A'] = gap_train.apply(lambda x: is_topic(x['A'].split(' '), x['topic']), axis=1)
gap_test['topic_A'] = gap_test.apply(lambda x: is_topic(x['A'].split(' '), x['topic']), axis=1)
gap_valid['topic_A'] = gap_valid.apply(lambda x: is_topic(x['A'].split(' '), x['topic']), axis=1)

gap_train['topic_B'] = gap_train.apply(lambda x: is_topic(x['B'].split(' '), x['topic']), axis=1)
gap_test['topic_B'] = gap_test.apply(lambda x: is_topic(x['B'].split(' '), x['topic']), axis=1)
gap_valid['topic_B'] = gap_valid.apply(lambda x: is_topic(x['B'].split(' '), x['topic']), axis=1)

In [7]:
gap_train.head(5)

,ID,Text,Pronoun,Pronoun-offset,A,A-offset,A-coref,B,B-offset,B-coref,...,pron_vector,name_list,name_list_2,neither_idx,neither_idx_2,neither_vector,neither_vector_2,topic,topic_A,topic_B
0,test-1,Upon their acceptance into the Kontinental Hoc...,His,383,Bob Suter,352,False,Dehner,366,True,...,"[[0.6202348, -0.49657542, 0.5204739, -0.727411...","[(Dehner, 58), (Gary, 320), (Suter, 325), (Bob...","[(Gary, 320), (Ryan, 432)]","[13, 14, 15, 85, 86, 87, 88, 120, 121, 122, 123]","[85, 86, 120, 121]","[[0.43322292, 0.79829735, -0.15718476, 0.42089...","[[0.7398826, 0.26755247, 0.29362696, 0.3004961...","[Jeremy, Dehner]",0,1
1,test-2,"Between the years 1979-1981, River won four lo...",him,430,Alonso,353,True,Alfredo Di St*fano,390,False,...,"[[0.6709301, -0.5158502, 0.73226666, -0.564204...","[(Alonso, 353), (Alfredo, 390), (Di, 398), (St...","[((, 409), (Carlos, 493), (Daniel, 500), (Tapi...","[109, 125, 126, 127, 128, 129, 130, 131, 133, ...","[109, 125, 126, 127, 128, 129, 130, 131, 133, ...","[[0.4568775, 0.943457, -1.0240802, 0.35397953,...","[[0.4568775, 0.943457, -1.0240802, 0.35397953,...","[Norberto, Alonso]",1,0
2,test-3,Though his emigration from the country has aff...,He,312,Ali Aladhadh,256,True,Saddam,295,False,...,"[[0.37514523, -0.4730158, 0.10452151, -0.03368...","[(Kamel, 75), (Hussien, 139), (Ali, 177), (Ala...","[(Kamel, 75), (Hussien, 139)]","[13, 14, 28, 29, 30, 40, 41, 42, 43, 44, 45]","[13, 14, 28, 29, 30]","[[-0.24583033, 0.5785628, -0.45035437, 0.90760...","[[-0.24583033, 0.5785628, -0.45035437, 0.90760...",[Aladhadh],1,0
3,test-4,"At the trial, Pisciotta said: ``Those who have...",his,526,Alliata,377,False,Pisciotta,536,True,...,"[[0.6802153, -0.041674256, 0.36125743, 0.46846...","[(Pisciotta, 14), (Bernardo, 78), (Mattarella,...","[(Bernardo, 78), (Mattarella, 87), (Marchesano...","[5, 6, 7, 8, 22, 23, 24, 25, 26, 27, 30, 31, 3...","[22, 23, 24, 25, 26, 27, 39, 40, 41, 44, 45, 4...","[[-0.63530976, 0.19418138, -0.26388228, 0.1768...","[[0.041738294, -0.06563458, -0.31707367, -0.90...","[Gaspare, Pisciotta]",0,1
4,test-5,It is about a pair of United States Navy shore...,his,406,Eddie,421,True,Rock Reilly,559,False,...,"[[0.31947732, -0.5680447, 1.1254325, -0.703441...","[(Tom, 65), (Berenger, 69), (William, 82), (Mc...","[(Tom, 65), (Berenger, 69), (William, 82), (Mc...","[18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 3...","[18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 3...","[[0.6178753, 0.7156216, 0.06808539, 0.4111841,...","[[0.6178753, 0.7156216, 0.06808539, 0.4111841,...",[Chasers],0,0

In [8]:
gap_train.to_pickle('./temp_result/train_kaggle_processed_PPA_PCA_PPA_neither_topic.p')
gap_test.to_pickle('./temp_result/test_kaggle_processed_PPA_PCA_PPA_neither_topic.p')
gap_valid.to_pickle('./temp_result/valid_kaggle_processed_PPA_PCA_PPA_neither_topic.p')